version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: splapp_image
    volumes:
      - /Users/jamesroe/Desktop/SPLAP_2/public:/var/www/html/public
    container_name: splapp_container
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/jamesroe/Desktop/SPLAP_2/public:/var/www/html/public
    ports:
      - "8001:80"
    depends_on:
      - app
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3303:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080